### ISSUE TITLE
tagを編集した後、ページを更新しても編集後のtagが残る様にしたいです。

### ISSUE THREAD

**Issue by yoshida-riki** [yoshida-riki/TimeOverGrow-new#57]
# What/Why
#13 の実装にあたり「tagを編集した後、ページを更新しても編集後のtagが残る様にしたい」と考えております。
しかし、Slackでもアドバイスを頂いた様に、「受け取った値をフロント側で整形してvuetifyのコンポーネントに食わせる」という作業がどうしてもうまくいかず困っておりますので、以下の仕様のレビューをお願い致します。

# 仕様(仮)

- 最初から6個tagが入っている状態(HTML,CSS,JavaScript,Vue.js,React.js,TypeScript)

- 最初からある6個のtagに関してはユーザーが自由に変更可能

- colorはそのまま文字列としてTextBox.vueに残しておくのはあまりにも見栄えが悪いのでFirestoreにtextと一緒に格納したいと考えております。

# 行ったこと

- まず「messages」コレクションとは別に、あらかじめtagのcolorとtextの値が格納されている「tags」コレクションを生成する為のTag.jsファイルを作りました。

- mountedメソッドの中でTag.jsのcolor,textの値を取得し、dataの中へ入れようと試みました。
→ここが難しく苦戦している状況です。それにmountedメソッドの中に記述している為リロードの度にcolor,textの値を保存してしまいデータがかさばってしまう状況です。

また、data()のitemsの配列の中に
```
{
  color: 'pruple',
  text: 'HTML'
}
```
の様にオブジェクトを合計6つ格納出来ず苦戦しております。

Firestoreからデータを
```
color = ['purple', 'indigo', 'blue', 'green', 'red', 'orange']
text = ['HTML', 'CSS', 'JavaScript', 'Vue.js', 'React.js', 'TypeScript']
```
という形式で取得することはできております。

# Reference
[こちら](https://v2.vuetifyjs.com/ja/components/combobox/#%E9%AB%98%E5%BA%A6%E3%81%AA%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3)のVuetifyのドキュメントを参考に実装しております。

**Comment by TakehiroTada** [comment]
まず、 `受け取った値をフロント側で整形してvuetifyのコンポーネントに食わせる` をどうやったら出来るかを落ち着いて考えましょう。

vue.jsには `computed` という便利な算出プロパティと呼ばれるものがあります。これを利用すると良いですね
https://jp.vuejs.org/v2/guide/computed.html


「受け取った値」→「computedで期待する値に整形」→「computedで作ったものをvuetifyにpropsで渡す」

という流れを組む必要があります

**Comment by yoshida-riki** [comment]
ありがとうございます！
確認致します！
